# import mantid algorithms, numpy and matplotlib
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np


def generate_input_path_for_run(run_number, cycle):
    return f"/archive/ndxosiris/Instrument/data/{cycle}/OSI{run_number}.nxs"

# To change by automatic script
input_runs = ["108538", "108539"]
# This needs to be loaded from a shared repository of files
calibration_file_path = "/extras/osi92682_multi_graphite002_calib.nxs"
cycle = "cycle_14_1"
analyser = "graphite"
reflection = "002"
spectroscopy_reduction = False
diffraction_reduction = False

# Defaults
instrument = "OSIRIS"
workspace_start_of_file = ""
efixed = 1.845
spec_spectra_range = "963,1004"
diff_spectra_range = '3,962'
# Grouping string is for 14 groups, and generated by the UI for indirect data reduction and based on spectra_range
grouping_string = "963-965,966-968,969-971,972-974,975-977,978-980,981-983,984-986,987-989,990-992,993-995,996-998,999-1001,1002-1004"
unit_x = "DeltaE"
fold_multiple_frames = False

# Generated
sum_runs = len(input_runs) > 1

input_file_paths = ""
for input_run in input_runs:
    input_file_paths += ", " + generate_input_path_for_run(input_run, cycle)
input_file_paths = input_file_paths[2:]  # Slice out the excess ", "
print(input_file_paths)

output_workspaces = []

# Perform the reduction
if spectroscopy_reduction:
    output_workspace_prefix = instrument
    for input_run in input_runs:
        output_workspace_prefix += input_run + ", "
    output_workspace_prefix = output_workspace_prefix[:-2] + f"_{analyser}_{reflection}_Reduced"  # Slice out the excess ", " and finalize prefix
    
    print("Producing a spectroscopy reduction")
    # Load calibration workspace
    calibration_workspace = Load(calibration_file_path)
    
    print("Reducing all")
    output_spec_ws_all = ISISIndirectEnergyTransferWrapper(OutputWorkspace=output_workspace_prefix + "-all", GroupingMethod="All", InputFiles=input_file_paths, SumFiles=sum_runs, CalibrationWorkspace=calibration_workspace, Instrument=instrument, Analyser=analyser, Reflection=reflection, EFixed=efixed, SpectraRange=spec_spectra_range, FoldMultipleFrames=fold_multiple_frames, UnitX=unit_x)

    print("Reducing using groups")
    output_spec_ws_grouping = ISISIndirectEnergyTransferWrapper(OutputWorkspace=output_workspace_prefix + "-groups", GroupingMethod="Custom", GroupingString=grouping_string, InputFiles=input_file_paths, SumFiles=sum_runs, CalibrationWorkspace=calibration_workspace, Instrument=instrument, Analyser=analyser, Reflection=reflection, EFixed=efixed, SpectraRange=spec_spectra_range, FoldMultipleFrames=fold_multiple_frames, UnitX=unit_x)

    print("Reducing individual")
    output_spec_ws_individual = ISISIndirectEnergyTransferWrapper(OutputWorkspace=output_workspace_prefix + "-individual", GroupingMethod="Individual", InputFiles=input_file_paths, SumFiles=sum_runs, CalibrationWorkspace=calibration_workspace, Instrument=instrument, Analyser=analyser, Reflection=reflection, EFixed=efixed, SpectraRange=spec_spectra_range, FoldMultipleFrames=fold_multiple_frames, UnitX=unit_x)
    
    output_workspaces.append(output_spec_ws_all)
    output_workspaces.append(output_spec_ws_grouping)
    output_workspaces.append(output_spec_ws_individual)

    # Also perform the diffspec reduction using the diffraction algorithm
    print("Reducing in diffspec mode using diffraction algorithm")
    output_ws = ISISIndirectDiffractionReduction(InputFiles=input_file_paths, CalFile=calibration_file_path, Instrument=instrument, SpectraRange=diff_spectra_range, OutputWorkspace=f"{instrument}{input_runs[0]}_diffspec_red")
    output_workspaces.append(output_ws)

elif diffraction_reduction:
    print("Producing a diffraction reduction")
    for run_number in input_runs:
        ws_name = instrument + run_number
        drange_ws = OSIRISDiffractionReduction(Sample=ws_name, CalFile=calibration_file_path, OutputWorkspace=f'{ws_name}_dRange')
        q_ws = ConvertUnits(InputWorkspace=drange_ws, OutputWorkspace=f'{ws_name}_q', Target='QSquared')
        tof_ws = ConvertUnits(InputWorkspace=drange_ws, OutputWorkspace=f'{ws_name}_tof', Target='TOF')
        output_workspaces.append(drange_ws)
        output_workspaces.append(q_ws)
        output_workspaces.append(tof_ws)
else:
    raise RuntimeError("Both spectroscopy_reduction and diffraction_reduction are set to false.")
            
output = []
for workspace in output_workspaces:
    save_file_name = f"{output_ws.name()}.nxs"
    save_path = f"/output/{save_file_name}"
    SaveNexusProcessed(workspace, save_path)
    output.append(save_file_name)
